// <auto-generated />
using System;
using DXApplicationStringFormat.Module.BusinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DXApplicationStringFormat.Module.Migrations
{
    [DbContext(typeof(DXApplicationStringFormatEFCoreDbContext))]
    partial class DXApplicationStringFormatEFCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Proxies:ChangeTracking", true)
                .HasAnnotation("Proxies:CheckEquality", true)
                .HasAnnotation("Proxies:LazyLoading", false)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DXApplicationStringFormat.Module.BusinessObjects.CostoCorso", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DurataFinoA")
                        .HasColumnType("int");

                    b.Property<int>("TipoCorso")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("TariffeAttestati");
                });
#pragma warning restore 612, 618
        }
    }
}
